server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ww67652/soa-config.git #GitHub上面的git仓库名字
          #uri: git@github.com:ww67652/springcloud-config.git
          ####搜索目录
          search-paths:
            - soa-config
#          force-pull: true
#          username: ww67652
#          password: 67652wuwei
#      ####读取分支
#      label: main
  #rabbitmq相关配置<--------------------------
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka  # http://eureka7002.com:7002/eureka
  instance:
    prefer-ip-address: true
    instance-id: config3344


##rabbitmq相关配置,暴露bus刷新配置的端点<--------------------------
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
