server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  #############################新增网关配置###########################
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: user_routh #user_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-user-service #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**         # 断言，路径相匹配的进行路由

        - id: tweet_routh #user_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-tweet-service #匹配后提供服务的路由地址
          predicates:
            - Path=/tweet/**         # 断言，路径相匹配的进行路由

        - id: tweet_routh #user_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-recruitment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/recruit/**         # 断言，路径相匹配的进行路由

#        - id: user_routh #user_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          #uri: lb://cloud-user-service #匹配后提供服务的路由地址
#          predicates:
#            - Path=/user/lb/**         # 断言，路径相匹配的进行路由
####################################################################

eureka:
  instance:
    prefer-ip-address: true
    instance-id: gateway9527
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #hostname: ${eureka.instance.ip-address}
    ip-address: 175.24.202.178
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka

