server:
  port: 8003 #服务端口
spring:
  application:
    name: cloud-tweet-service #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://175.24.202.178:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: Jwl12345
  #文件传输大小配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB  #单个文件最大大小
      max-request-size: 6000MB #上传数据总大小
devtools:
  restart:
    enabled: true #是否支持热部署

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.soa.springcloud.entities  #所有entity别名所在包

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka  # http://eureka7002.com:7002/eureka
  instance:
    instance-id: tweet8003

file:
  localPath: "C:\\upload"
  webPath: "http://47.102.217.130:666"