server:
  port: 8003 #服务端口
spring:
  application:
    name: cloud-tweet-service #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://175.24.202.178:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: Jwl12345
  #文件传输大小配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB  #单个文件最大大小
      max-request-size: 6000MB #上传数据总大小
devtools:
  restart:
    enabled: true #是否支持热部署

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.soa.springcloud.entities  #所有entity别名所在包

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: tweet8003
    ip-address: 175.24.202.178

file:
  localPath: "C:\\upload"
  webPath: "http://175.24.202.178:666"

#设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#开启服务降级
feign:
  hystrix:
    enabled: true